### ISSUE TITLE
Instructions in  README.md doesn't have the credentials template configuration

### ISSUE THREAD

**Issue by Berriss** [Autodesk-Forge/viewer-react-express-headless#18]
> Development mode
Follow these instructions to get the app running locally:

> 1.run git clone this repository
2.cd into the project's directory
3.create a file called server/credentials.js with your credentials, follow **this template**
4.run npm install
5.run npm run watch

> This will get a server running locally, open http://localhost:3000 on your browser to see the app running.

I want to learn how to setup this App but The 'template' link is bronken.

**Comment by jaimerosales** [comment]
Thanks for letting me know, I missed this when I transfer the sample from my own repo. It is fixed now and you should be able to continue #19
