### ISSUE TITLE
Heroku React Issue

### ISSUE THREAD

**Issue by mbhawkeye** [Autodesk-Forge/viewer-react-express-headless#33]
Hi!

I tried forking & deploying to Heroku but it gets hung up pretty early on when calling react-scripts build. The only change I made was adding my credentials. Any idea if there's an easy fix to this? I love the style of the viewer and was hoping to play around with it a bit. 

       > viewer-server@0.0.1 build /tmp/build_a500c81f59799abc10fd0ba4c5d858f9
       > react-scripts build
       
       /tmp/build_a500c81f59799abc10fd0ba4c5d858f9/node_modules/react-scripts/config/webpack.config.js:318
               ...(isEnvProductionProfile && {
               ^^^
       SyntaxError: Unexpected token ...
           at Object.exports.runInThisContext (vm.js:76:16)
           at Module._compile (module.js:528:28)
           at Object.Module._extensions..js (module.js:565:10)
           at Module.load (module.js:473:32)
           at tryModuleLoad (module.js:432:12)
           at Function.Module._load (module.js:424:3)
           at Module.require (module.js:483:17)
           at require (internal/module.js:20:19)
           at Object.<anonymous> (/tmp/build_a500c81f59799abc10fd0ba4c5d858f9/node_modules/react-scripts/scripts/build.js:38:23)
           at Module._compile (module.js:556:32)
       ///
       npm ERR! Linux 4.4.0-1048-aws
       npm ERR! argv "/tmp/build_a500c81f59799abc10fd0ba4c5d858f9/.heroku/node/bin/node" "/tmp/build_a500c81f59799abc10fd0ba4c5d858f9/.heroku/node/bin/npm" "run" "build"
       npm ERR! node v6.7.0
       npm ERR! npm  v3.10.10
       npm ERR! code ELIFECYCLE
       npm ERR! viewer-server@0.0.1 build: `react-scripts build`
       npm ERR! Exit status 1
       npm ERR! 
       npm ERR! Failed at the viewer-server@0.0.1 build script 'react-scripts build'.
       npm ERR! Make sure you have the latest version of node.js and npm installed.
       npm ERR! If you do, this is most likely a problem with the viewer-server package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     react-scripts build
       npm ERR! You can get information on how to open an issue for this project with:
       npm ERR!     npm bugs viewer-server
       npm ERR! Or if that isn't available, you can get their info via:
       npm ERR!     npm owner ls viewer-server
       npm ERR! There is likely additional logging output above.
       
       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/build_a500c81f59799abc10fd0ba4c5d858f9/npm-debug.log
       `

**Comment by jaimerosales** [comment]
Just adding the credentials will not make this sample run. Since the URN's of the Models are connected to my account only. You would need to Translate your own models, and replace the existing ones with the new URN's that will be part of your account. 

I will say run this locally first, once that works you can move ahead to host it in Heroku. 

What specific part of the layout of the viewer do you like? It might be easier to replicate that without the need of this entire project. I did it for another sample just recently took me less than an hour to have it running. is it the Headless way? or something more specific?

**Comment by mbhawkeye** [comment]
Thank you! I had just tried hitting the deploy button to see if I could get it to run before I modified it, I was able to get it running locally with no issues aside from the URNs. 

I'm pretty new to working with forge, I really liked the headless layout with the individual selectable model views on the bottom as well as how properties are displayed in the model view. It's really minimal and perfect for something I wanted to demonstrate.

**Comment by jaimerosales** [comment]
I will say Translate your own models, place them in a persistent bucket so they don't delete after 24 hours and get the URN's. I have a set of Insomnia REST collections to use the Data Management (OSS) service and also the Model Derivative Translator. You can find them here. https://github.com/jaimerosales/AutodeskForge-Insomnia-Collections 

Use this to do the workflow of uploading the models to your own bucket, translating and getting the URN values to replace them. So you can continue using the UX UI of the sample. LEt me know how it goes.

**Comment by mbhawkeye** [comment]
I did manage to finally get this working. It ran without any trouble locally but I was still seeing the same deployment errors from heroku after swapping in my URN's and other relevant info, I updated the node & npm versions in package.json with more recent versions (node 12.13.x, npm 6.12.x) and it ended up deploying just fine. 

Thank you for your help!
