### ISSUE TITLE
.dwg support

### ISSUE THREAD

**Issue by oguzhannkayaa** [Autodesk-Forge/viewer-react-express-headless#65]
Is there dwg support in application and also drag and drop parts?

**Comment by petrbroz** [comment]
In general, the [Viewer SDK](https://aps.autodesk.com/en/docs/viewer/v7/reference/Viewing/Viewer3D/) does support DWG through the Model Derivative service (here's a [list of all supported formats](https://aps.autodesk.com/en/docs/model-derivative/v2/developers_guide/supported-translations/)), and it also lets you customize the viewer behavior to add support for drag&drop ([blog](https://aps.autodesk.com/blog/drag-and-drop-models-viewer)).
