### ISSUE TITLE
My result

### ISSUE THREAD

**Issue by Mykita** [Autodesk-Forge/viewer-react-express-headless#7]
Hi!
I forked my own _viewer-react-express-headless_ and edited the _credentials.js_ and Deployed to Heroku.

Here is my result: https://immense-fortress-56268.herokuapp.com/

It doesnt seem like it's quite working. Neither of the models loads. What could be the problems?

Kind regards.

**Comment by jaimerosales** [comment]
Hi Mykita,

The sample is setup as a template where you will need to translate your own models with you own set of keys. If you see the component gallery I have data that contains the URN for all the models. You will need to replace these ones with your own. 

Also to restore the state the values will be different, but let's start first with the loading of your own models.

Cheers,
Jaime

**Comment by Mykita** [comment]
Thank you! I did figure this out after some debugging :D I also asked a question over at SO: https://stackoverflow.com/questions/45411476/github-viewer-react-express-headless/45412683#45412683
Everything is sorted and my page is working with one of my URNs: https://limitless-wave-castle.herokuapp.com/

By the way. This is amazing! I really love the UI and the overall set up. Insanely good job Jamie! I will be using this a lot in the future.

**Comment by jaimerosales** [comment]
Thank you for the kind words :) One last thing I can suggest, also replace the URN here 
https://github.com/Autodesk-Forge/viewer-react-express-headless/blob/master/src/components/Viewer/Viewer.js#L26 So at the time of loading you can get your model with out the need of clicking anywhere. 

Later on, you can add your own Thumbnails, and Logo to your site. Glad you are enjoying it! ![bitmoji](https://render.bitstrips.com/v2/cpanel/10212734-252915081_1-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by Mykita** [comment]
Perfect!
I am curious whether you received my recent email. Thought I'd ask you a question relevant to this repo :)
